config/routes.rb
AntiKb::Application.routes.draw do
  root 'home#index'

  if Rails.env.production?
    mount LetsEncrypt::Engine => '/.well-known'
  end


  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords" }, :path_names => { :sign_up => 'new', :sign_in => 'login', :sign_out => 'logout' }
  as :user do
    get '/users/presign', to: 'users/sessions#presign', as: :user_presign
  end

  resources :users do
    member do
      put 'like', to: 'users#upvote'
      put 'dislike', to: 'users#downvote'
    end
  end

  resources :reports do
    member do
      put 'like', to: 'reports#upvote'
      put 'dislike', to: 'reports#downvote'
    end
  end

  resources :compliments do
    member do
      put 'like', to: 'compliments#upvote'
      put 'dislike', to: 'compliments#downvote'
    end
  end

  resources :models do
    member do
      put 'like', to: 'models#upvote'
      put 'dislike', to: 'models#downvote'
    end
  end

  resources :comments, only: :destroy

  resources :articles, :intro, :improve, :sitemap, :faqs, :faq_categories, :proposes, :notices, :galleries
  get 'kbsmind', to: 'home#kbsmind'
  get 'feed', to: 'home#feed'
  get 'privacy', to: 'home#privacy'
  get 'user-delete-confirm', :to=>'users#delete_confirm', as: 'delete_confirm_user'
  get 'users/add_new_comment/:id', to: 'users#new_comment', as: 'new_comment_to_users'
  post 'users/add_new_comment', to: 'users#create_comment', as: 'create_comment_to_users'

  get 'home', to: 'home#index'
  scope 'admin', module: 'admin', as: 'admin' do
    get '/' => 'admin_home#index'
    resources :users, :articles, :improve, :faq_categories, :faqs, :proposes, :compliment_categories, :compliments, :report_categories, :reports, :notices, :models, :banks
  end
end

app/models/faq_category.rb
class FaqCategory < ApplicationRecord
  validates_presence_of :title
  has_many :faq, :dependent => :destroy
end

app/controllers/admin/faq_categories_controller.rb
class Admin::FaqCategoriesController < Admin::AdminController
  before_action :set_admin_faq_category, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)

    @category = t(:menu_main_board,scope:[:admin_menu])
    @controller_name = t('activerecord.models.faq_category')
  end

  # GET /admin/faq_categories
  # GET /admin/faq_categories.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    @admin_faq_categories = FaqCategory.order('id desc').page(params[:page]).per(params[:per_page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @admin_blog_categories }
    end
  end

  # GET /admin/faq_categories/1
  # GET /admin/faq_categories/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_faq_category }
    end
  end

  # GET /admin/faq_categories/new
  # GET /admin/faq_categories/new.json
  def new
    @admin_faq_category = FaqCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_faq_category }
    end
  end

  # GET /admin/faq_categories/1/edit
  def edit
  end

  # POST /admin/faq_categories
  # POST /admin/faq_categories.json
  def create
    @admin_faq_category = FaqCategory.new(admin_faq_category_params)

    respond_to do |format|
      if @admin_faq_category.save
        format.html { redirect_to admin_faq_category_path(@admin_faq_category), notice: @controller_name + t(:message_success_create)}
        format.json { render json: @admin_faq_category, status: :created, location: @admin_faq_category }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_faq_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/faq_categories/1
  # PUT /admin/faq_categories/1.json
  def update
    respond_to do |format|
      if @admin_faq_category.update_attributes(admin_faq_category_params)
        format.html { redirect_to admin_faq_category_path(@admin_faq_category), notice: @controller_name + t(:message_success_update)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_faq_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/faq_categories/1
  # DELETE /admin/faq_categories/1.json
  def destroy
    @admin_faq_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_faq_categories_path}
      format.json { head :ok }
    end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_faq_category
      @admin_faq_category = FaqCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_faq_category_params
      params.require(:faq_category).permit(:id,:faq_category_id,:title)
    end
end

app/controllers/faq_categories_controller.rb
class FaqCategoriesController < BoardController
  before_action :set_faq_category, only: [:show]

  def initialize(*params)
    super(*params)
    @controller_name=t('activerecord.models.faq_category')
    @title=@controller_name
  end

  # GET /faq_categories
  # GET /faq_categories.json
  def index
    @faq_categories = FaqCategory.order('id desc').page(params[:page]).per(10)
    @script='board/faqs/index'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faq_categories }
    end
  end

  # GET /faq_categories/1
  # GET /faq_categories/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq_category }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq_category
      @faq_category = FaqCategory.find(params[:id])
    end
end

app/views/admin/faq_categories/_form.html.erb
<%= form_for [:admin,faq_category] do |f| %>
<% if faq_category.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
	<a href="#" class="close" data-dismiss="alert">&times;</a>
	<h2><%= pluralize(faq_category.errors.count, "error") %> prohibited this request from being saved:</h2>
	<ul>
		<% faq_category.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="form-group">
	<%= f.label :title %>
	<%= f.text_field :title,:class=>"form-control",:required=>"required" %>
</div>
<div class="form-group">
	<%= f.label :enable %>
	<%= f.check_box :enable %>
</div>
<div class="form-group actions">
	<%= f.submit :class=>"btn btn-primary" %>
</div>
<% end %>

app/views/admin/faq_categories/edit.html.erb
<%= render 'form',:faq_category=>@admin_faq_category %>
<%= link_to t(:link_show), admin_faq_path(@admin_faq_category) %> |
<%= link_to t(:link_list), admin_faq_categories_path %>

app/views/admin/faq_categories/index.html.erb
<div class="row">
	<h3 class="col-xs-12 col-sm-6"><%= @controller_name %> <%= actionNameChange controller.action_name %></h3>
	<div class="col-xs-12 col-sm-6">

	</div>
</div>
<div class="table-responsive">
	<table class="table table-bordered table-striped">
		<colgroup>
      <col style="width:100px" />
      <col />
      <col style="width:130px" />
      <col style="width:100px" />
      <col style="width:130px" />
      <% if can?(:update, FaqCategory) || can?(:delete, FaqCategory) %>
      <col <%=raw manage_width(FaqCategory) %> />
      <% end %>
    </colgroup>
		<thead>
			<tr>
				<th><%= t(:label_number) %></th>
				<th><%=t(:title,scope:[:activerecord,:attributes,:faq_category]) %></th>
				<th><%=t(:faqs_count,scope:[:activerecord,:attributes,:faq_category]) %></th>
				<th><%=t(:enable,scope:[:activerecord,:attributes,:faq_category]) %></th>
				<th><%= t(:label_created_at) %></th>
				<% if can?(:update, FaqCategory) || can?(:delete, FaqCategory) %>
				<th><%= t(:label_manage) %></th>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<% unless @admin_faq_categories.empty? %>
			<% @admin_faq_categories.each do |faq_category| %>
			<tr>
				<td><%= link_to faq_category.id,admin_faq_category_path(faq_category) %></td>
				<td><%= link_to faq_category.title,admin_faq_category_path(faq_category) %></td>
				<td><%= link_to faq_category.faqs_count,admin_faqs_path(:faq_category_id=>faq_category.id) %></td>
				<td><%= raw flagToString(faq_category.enable) %></td>
				<td><%= faq_category.created_at.to_date %></td>
				<% if can?(:update, faq_category) || can?(:delete, faq_category) %>
				<td> <% if can? :update, faq_category %>
				<%= link_to edit_admin_faq_category_path(faq_category),:class=>"btn btn-default" do %> <i class="glyphicon glyphicon-pencil"></i> <%= t(:link_edit) %>
				<% end %>
				<% end %>
				<% if can? :delete, faq_category %>
				<%= link_to admin_faq_category_path(faq_category), :method => :delete, :data => { :confirm => t(:delete_confirm) },:class=>"btn btn-danger" do %> <i class="glyphicon glyphicon-trash"></i> <%= t(:link_delete) %>
				<% end %>
				<% end %> </td>
				<% end %>
			</tr>
			<% end %>
			<% else %>
			<tr>
				<td colspan="6"><%= t(:no_data)%></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="row">
	<div class="col-xs-6 col-sm-3 col-md-2">
		<% if can? :create, FaqCategory %>
		<%= link_to new_admin_faq_category_path,:class=>"btn btn-primary" do %>
		<i class="glyphicon glyphicon-plus"></i> <%= t(:link_new) %>
		<% end %>
		<% end %>
	</div>
	<nav class="col-xs-12 col-sm-9 col-md-10">
		<%= paginate @admin_faq_categories %>
	</nav>
</div>

app/views/admin/faq_categories/new.html.erb
<%= render 'form',:faq_category=>@admin_faq_category %>
<%= link_to t(:link_list), admin_faq_categories_path %>

app/views/admin/faq_categories/show.html.erb
<div class="sl_show">
	<p>
		<b><%=t(:title,scope:[:activerecord,:attributes,:faq_category]) %></b>
		<%= @faq_category.title %>
	</p>
	<p>
		<b><%=t(:faqs_count,scope:[:activerecord,:attributes,:faq_category]) %></b>
		<%= @faq_category.faqs_count %>
	</p>
	<p>
		<b><%=t(:enable,scope:[:activerecord,:attributes,:faq_category]) %></b>
		<%=raw flagToString(@faq_category.enable) %>
	</p>
	<p>
  	<b><%=t(:label_created_at) %></b>
  	<%= @faq_category.created_at %>
  </p>
  <p>
  	<b><%=t(:label_updated_at) %></b>
  	<%= @faq_category.created_at %>
  </p>
</div>
<% if can? :update, @faq_category %>
<%= link_to t(:link_edit), edit_admin_faq_category_path(@faq_category) %> |
<% end %>
<%= link_to t(:link_list), admin_faq_categories_path %>