config/routes.rb
AntiKb::Application.routes.draw do
  root 'home#index'

  if Rails.env.production?
    mount LetsEncrypt::Engine => '/.well-known'
  end


  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords" }, :path_names => { :sign_up => 'new', :sign_in => 'login', :sign_out => 'logout' }
  as :user do
    get '/users/presign', to: 'users/sessions#presign', as: :user_presign
  end

  resources :users do
    member do
      put 'like', to: 'users#upvote'
      put 'dislike', to: 'users#downvote'
    end
  end

  resources :reports do
    member do
      put 'like', to: 'reports#upvote'
      put 'dislike', to: 'reports#downvote'
    end
  end

  resources :compliments do
    member do
      put 'like', to: 'compliments#upvote'
      put 'dislike', to: 'compliments#downvote'
    end
  end

  resources :models do
    member do
      put 'like', to: 'models#upvote'
      put 'dislike', to: 'models#downvote'
    end
  end

  resources :comments, only: :destroy

  resources :articles, :intro, :improve, :sitemap, :faqs, :faq_categories, :proposes, :notices, :galleries
  get 'kbsmind', to: 'home#kbsmind'
  get 'feed', to: 'home#feed'
  get 'privacy', to: 'home#privacy'
  get 'user-delete-confirm', :to=>'users#delete_confirm', as: 'delete_confirm_user'
  get 'users/add_new_comment/:id', to: 'users#new_comment', as: 'new_comment_to_users'
  post 'users/add_new_comment', to: 'users#create_comment', as: 'create_comment_to_users'

  get 'home', to: 'home#index'
  scope 'admin', module: 'admin', as: 'admin' do
    get '/' => 'admin_home#index'
    resources :users, :articles, :improve, :faq_categories, :faqs, :proposes, :compliment_categories, :compliments, :report_categories, :reports, :notices, :models, :banks
  end
end

app/models/faq.rb
class Faq < ApplicationRecord
  validates_presence_of :title
  belongs_to :faq_category, :autosave => true
  has_one :faq_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :faq
  accepts_nested_attributes_for :faq_content, :allow_destroy => true
end

app/controllers/admin/faqs_controller.rb
class Admin::FaqsController < Admin::AdminController
  before_action :set_admin_faq, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)

    @category = t(:menu_main_board,scope:[:admin_menu])
    @controller_name = t('activerecord.models.faq')
  end

  # GET /admin/faqs
  # GET /admin/faqs.json
  def index
      params[:per_page] = 10 unless params[:per_page].present?

      @admin_faq_categories=FaqCategory.where(:enable=>true)

      if(params[:blog_category_id])
        @admin_faq_category_id=params[:faq_category_id].to_i
        @admin_faqs = Faq.where(:faq_category_id=>@admin_faq_category_id).order(id:'desc').page(params[:page]).per(params[:per_page])
      else
        @admin_faqs = Faq.order('id desc').page(params[:page]).per(params[:per_page])
      end

    respond_to do |format|
      format.html
      format.json { render json: @admin_faqs }
    end
  end

  # GET /admin/faqs/1
  # GET /admin/faqs/1.json
  def show
    @admin_faq_content=FaqContent.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_faqContent }
    end
  end

  # GET /admin/faqs/new
  # GET /admin/faqs/new.json
  def new
    @admin_faq = Faq.new
    @admin_faq.build_faq_content
    @admin_faq_categories = FaqCategory.all
    @admin_faq_category_id=params[:faq_category_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_faq }
    end
  end

  # GET /admin/faqs/1/edit
  def edit
    @admin_faq_categories = FaqCategory.all
    @admin_faq_category_id=@admin_faq.faq_category.id
  end

  # POST /admin/faqs
  # POST /admin/faqs.json
  def create
    @admin_faq = Faq.new(admin_faq_params)

    respond_to do |format|
      if @admin_faq.save
        format.html { redirect_to admin_faq_path(@admin_faq), :notice=> @controller_name +t(:message_success_create)}
        format.json { render json: @admin_faq, status: :created, location: @admin_faq }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/faqs/1
  # PUT /admin/faqs/1.json
  def update
    @admin_faq = Faq.find(params[:id])

    respond_to do |format|
      if @admin_faq.update_attributes(admin_faq_params)
        format.html { redirect_to admin_faq_path(@admin_faq), :notice=> @controller_name +t(:message_success_update)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/faqs/1
  # DELETE /admin/faqs/1.json
  def destroy
    @admin_faq.destroy

    respond_to do |format|
      format.html { redirect_to admin_faqs_path}
      format.json { head :ok }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_admin_faq
    @admin_faq = Faq.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_faq_params
    params.require(:faq).permit(:id,:faq_category_id,:title, :enable, faq_content_attributes: [:id,:content])
  end
end

app/controllers/faqs_controller.rb
class FaqsController < BoardController
  before_action :set_faq, only: [:show]

  def initialize(*params)
    super(*params)
    @controller_name=t('activerecord.models.faq')
    @title=@controller_name
    @page_itemtype='http://schema.org/QAPage'    
  end

  # GET /faqs
  # GET /faqs.json
  def index
    @faq_categories = FaqCategory.all

    if(params[:faq_category_id])
      @categoryId=params[:faq_category_id].to_i
    else
      if @faq_categories[0]
        @categoryId=@faq_categories[0].id.to_i
      else
        @categoryId=nil
      end
    end

    @faqs = Faq.where(:faq_category_id=>@categoryId).order('id desc').page(params[:page]).per(10)

    admin=false
    if(current_user)
      if(current_user.admin)
        admin=true
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:faqs=>@faqs,:admin=>admin} }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq_categories = FaqCategory.all

    if(params[:id])
      @faq = Faq.find(params[:id])
    end

    @title=@faq.title
    @meta_description=@faq.faq_content.content

    if(params[:faq_category_id])
      @categoryId=params[:faq_category_id].to_i
    else
      @categoryId=@faq.faq_category_id
    end

    @faqs = Faq.where(:faq_category_id=>@categoryId).order('id desc').page(params[:page]).per(10)

    admin=false
    if(current_user)
      if(current_user.admin)
        admin=true
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faq.faq_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end
end

app/views/faqs/_form.html.erb
<%= form_for @faq, :html => { :class => 'col-12' } do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>
      <ul>
        <% @faq.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :faq_category_id %><br/>
    <%= f.select :faq_category_id, options_from_collection_for_select(@faq_categories, 'id', 'title', @faq_category_id) %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, :class => 'sl_input', :required => 'required' %>
  </div>
  <%= f.fields_for :faq_content do |c| %>
    <div class="form-group">
      <%= c.label :content %><br/>
      <%= c.text_area :content, :class => 'sl_input', :required => 'required' %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<div id="faq_edit">
	<%= render 'form' %>
	<%= link_to t(:link_show), @faq %> |
	<%= link_to t(:link_list), faqs_path %>
</div>

app/views/faqs/index.html.erb
<% breadcrumb :faqs %>
<%
  if @faq_categories.count.zero?
    re=0
  else
    re=100/@faq_categories.count
  end

%>
<section id="faq_main">
	<article>
		<ol id="faqCategoryList">
			<% unless @faq_categories.empty? %>
			<% @faq_categories.each do |faq_category| %>
			<li <% if(@categoryId==faq_category.id) %>class="on"<% end %> style="width:<%=re %>%" >
				<%= link_to truncate(faq_category.title,:length => 20),faqs_path(:faq_category_id=>faq_category.id),{:class=>'title'} %>
				<% if(@categoryId==faq_category.id) %>
				<% if can?(:update, FaqCategory) || can?(:delete, FaqCategory) %>
				<div class="sl_faq_category_menu">
					<% if can? :update, FaqCategory %>
					<%= link_to t(:link_edit), edit_faq_category_path(faq_category) %>
					<% end %>
					<% if can? :delete, FaqCategory %>
					<% if can? :update, FaqCategory %>
					<br />
					<% end %>
					<%= link_to t(:link_delete), faq_category, method: :delete, data: { confirm: t(:delete_confirm) } %>
					<% end %>
				</div>
				<% end %>
				<% end %>
			</li>
			<% end %>
  		<% else %>
			<li><%=t(:no_data)%></li>
			<% end %>
		</ol>
	</article>
	<article>
		<dl id="faqList">
			<% unless @faqs.empty? %>
			<% @faqs.each do |faq| %>
			<dt <% if @faq %><% if @faq.id==faq.id %>class="on"<% end %><% end %>>
				<%= link_to truncate(faq.title,:length => 80), faq_path(faq),{:class=>'title'} %>
				<% if user_signed_in? %>
				<% if current_user.admin? %>
				<div class="sl_faq_menu">
					<%= link_to t(:link_edit), edit_faq_path(faq) %> &nbsp; | &nbsp; <%= link_to t(:link_delete), faq, method: :delete, data: { confirm: t(:delete_confirm) } %>
				</div>
				<% end %>
				<% end %>
			</dt>
			<% if(@faq)%>
			<% if(faq.id==@faq.id) %>
					<dd><%=simple_format(@faq.faq_content.content) %></dd>
			<% end %>
			<% end %>

			<% end %>
  			<% else %>
  			<dt><%=t(:no_data)%></dt>
			<% end %>
		</dl>
	</article>
	<div class="flickr_pagination">
		<%= paginate @faqs %>
  	</div>
	<div id="sl_bottom_menu">
		<% if user_signed_in? %>
		<% if current_user.admin? %>
		<%= link_to 'FAQ 분류 생성',new_faq_category_path %> &nbsp; | &nbsp; <%= link_to 'FAQ 생성',new_faq_path(:faq_category_id=>@categoryId) %>
		<% end %>
		<% end %>
	</div>
</section>

app/views/faqs/new.html.erb
<div id="faq_new">
	<%= render 'form' %>
	<%= link_to t(:link_list), faqs_path %>
</div>

app/views/faqs/show.html.erb
<% breadcrumb :faq,@faq %>
<% re=100/@faq_categories.count %>
<section id="sl_faq_index">
	<article>
		<ol id="faqCategoryList">
			<% unless @faq_categories.empty? %>
			<% @faq_categories.each do |faq_category| %>
			<li <% if(@categoryId==faq_category.id) %>class="on"<% end %> style="width:<%=re %>%" >
				<%= link_to truncate(faq_category.title,:length => 20),faqs_path(:faq_category_id=>faq_category.id),{:class=>'title'} %>
				<% if(@categoryId==faq_category.id) %>
				<% if user_signed_in? %>
				<% if current_user.admin? %>
				<div class="sl_faq_category_menu">
					<%= link_to t(:edit), edit_faq_category_path(faq_category) %><br />
					<%= link_to t(:delete), faq_category, method: :delete, data: { confirm: '정말로 삭제합니까?' } %>
				</div>
				<% end %>
				<% end %>
				<% end %>
			</li>
			<% end %>
  			<% else %>
			<li><%=t(:no_data) %></li>
			<% end %>
		</ol>
	</article>
	<article>
		<dl id="faqList">
			<% unless @faqs.empty? %>
			<% @faqs.each do |faq| %>
			<dt <% if @faq %><% if @faq.id==faq.id %>class="on"<% end %><% end %>>
				<%= link_to truncate(faq.title,:length => 80), faq_path(faq),{:class=>'title'} %>
				<% if user_signed_in? %>
				<% if current_user.admin? %>
				<div class="sl_faq_menu">
					<%= link_to t(:link_edit), edit_faq_path(faq) %> &nbsp; | &nbsp; <%= link_to t(:link_delete), faq, method: :delete, data: { confirm: t(:delete_confirm) } %>
				</div>
				<% end %>
				<% end %>
			</dt>
			<% if(@faq)%>
			<% if(faq.id==@faq.id) %>
					<dd><%=simple_format(@faq.faq_content.content) %></dd>
			<% end %>
			<% end %>

			<% end %>
  			<% else %>
  			<dt><%=t(:no_data)%></dt>
			<% end %>
		</dl>
	</article>
	<div class="flickr_pagination">
		<%= paginate @faqs %>
  	</div>
	<div id="sl_bottom_menu">
		<% if user_signed_in? %>
		<% if current_user.admin? %>
		<%= link_to 'FAQ 분류 생성',new_faq_category_path %> &nbsp; | &nbsp; <%= link_to 'FAQ 생성',new_faq_path(:faq_category_id=>@categoryId) %>
		<% end %>
		<% end %>
	</div>
</section>