config/routes.rb
AntiKb::Application.routes.draw do
  root 'home#index'

  if Rails.env.production?
    mount LetsEncrypt::Engine => '/.well-known'
  end


  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords" }, :path_names => { :sign_up => 'new', :sign_in => 'login', :sign_out => 'logout' }
  as :user do
    get '/users/presign', to: 'users/sessions#presign', as: :user_presign
  end

  resources :users do
    member do
      put 'like', to: 'users#upvote'
      put 'dislike', to: 'users#downvote'
    end
  end

  resources :reports do
    member do
      put 'like', to: 'reports#upvote'
      put 'dislike', to: 'reports#downvote'
    end
  end

  resources :compliments do
    member do
      put 'like', to: 'compliments#upvote'
      put 'dislike', to: 'compliments#downvote'
    end
  end

  resources :models do
    member do
      put 'like', to: 'models#upvote'
      put 'dislike', to: 'models#downvote'
    end
  end

  resources :comments, only: :destroy

  resources :articles, :intro, :improve, :sitemap, :faqs, :faq_categories, :proposes, :notices, :galleries
  get 'kbsmind', to: 'home#kbsmind'
  get 'feed', to: 'home#feed'
  get 'privacy', to: 'home#privacy'
  get 'user-delete-confirm', :to=>'users#delete_confirm', as: 'delete_confirm_user'
  get 'users/add_new_comment/:id', to: 'users#new_comment', as: 'new_comment_to_users'
  post 'users/add_new_comment', to: 'users#create_comment', as: 'create_comment_to_users'

  get 'home', to: 'home#index'
  scope 'admin', module: 'admin', as: 'admin' do
    get '/' => 'admin_home#index'
    resources :users, :articles, :improve, :faq_categories, :faqs, :proposes, :compliment_categories, :compliments, :report_categories, :reports, :notices, :models, :banks
  end
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :url
end

app/models/bank.rb
class Bank < ApplicationRecord
  validates_presence_of :title
  has_many :compliment, :dependent => :destroy
  mount_uploader :photo, BankPhotoUploader
end

app/models/comment.rb
class Comment < ApplicationRecord

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/compliment.rb
class Compliment < ApplicationRecord
  acts_as_votable
  acts_as_commentable
  is_impressionable
  validates_presence_of :title
  belongs_to :user, counter_cache: true
  belongs_to :bank, counter_cache: true
  belongs_to :compliment_category, counter_cache: true
  has_one :compliment_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :compliment
  accepts_nested_attributes_for :compliment_content, :allow_destroy => true, :update_only => true

  def compliment_content
    super || build_compliment_content
  end
end

app/models/faq.rb
class Faq < ApplicationRecord
  validates_presence_of :title
  belongs_to :faq_category, :autosave => true
  has_one :faq_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :faq
  accepts_nested_attributes_for :faq_content, :allow_destroy => true
end

app/models/faq_category.rb
class FaqCategory < ApplicationRecord
  validates_presence_of :title
  has_many :faq, :dependent => :destroy
end

app/models/faq_content.rb
class FaqContent < ApplicationRecord
  validates_presence_of :content
  belongs_to :faq, :foreign_key => :id, inverse_of: :faq_content
  accepts_nested_attributes_for :faq
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  validates_presence_of :title, :photo
  belongs_to :gallery_category
  mount_uploader :photo, GalleryPhotoUploader
end

app/models/improve.rb
class Improve < ApplicationRecord
  validates_presence_of :title, :content
end

app/models/model.rb
class Model < ApplicationRecord
  acts_as_votable
  acts_as_commentable
  validates_presence_of :title, :recommend_description, :models_comment
  belongs_to :user, :autosave => true
  has_many :model_comment, :dependent => :destroy
  accepts_nested_attributes_for :model_comment, :allow_destroy => true
  mount_uploader :photo, ModelPhotoUploader
end

app/models/model_comment.rb
class ModelComment < ApplicationRecord
  validates_presence_of :content
  belongs_to :model, :autosave => true, :counter_cache => true
  belongs_to :user, :autosave => true
  accepts_nested_attributes_for :model, :allow_destroy => true
end

app/models/notice.rb
class Notice < ApplicationRecord
  is_impressionable
  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60
  belongs_to :user, autosave: true
  has_one :notice_content, foreign_key: :id, dependent: :destroy, inverse_of: :notice
  accepts_nested_attributes_for :notice_content, allow_destroy: true, update_only: true

  def notice_content
    super || build_notice_content
  end
end

app/models/notice_content.rb
class NoticeContent < ApplicationRecord
  validates_presence_of :content
  belongs_to :notice, foreign_key: :id, inverse_of: :notice_content
end

app/models/propose.rb
class Propose < ApplicationRecord
  validates_presence_of :title
  belongs_to :user, :autosave => true
end

app/models/report.rb
class Report < ApplicationRecord
  acts_as_votable
  acts_as_commentable
  is_impressionable
  validates_presence_of :title
  belongs_to :user, counter_cache: true
  belongs_to :report_category, counter_cache: true
  has_one :report_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :report
  accepts_nested_attributes_for :report_content, :allow_destroy => true, :update_only => true

  def report_content
    super || build_report_content
  end
end

app/models/report_category.rb
class ReportCategory < ApplicationRecord
  validates_presence_of :title
  has_many :report, :dependent => :destroy
end

app/models/report_content.rb
class ReportContent < ApplicationRecord
  validates_presence_of :content
  belongs_to :report, :foreign_key => :id, inverse_of: :report_content
end

app/models/user.rb
class User < ApplicationRecord
  include OmniauthAttributesConcern
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  acts_as_voter
  acts_as_votable
  acts_as_commentable
  validates_presence_of :name, :email, :description, :on => :create
  validates_length_of :name, within: 1..60
  validates_length_of :email, within: 4..150
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_uniqueness_of :email

  validates_length_of :password, :within => 4..200, :allow_blank => true
  mount_uploader :photo, UserUploader
  has_many :user_authorizations

  def self.create_from_omniauth(params)
    self.__send__(params.provider, params)
  end
end

app/models/user_ability.rb
class UserAbility
  include CanCan::Ability

  def initialize(user)
    cannot :manage, :all
    can :create, [User]
    can :manage, [User, Propose, Model, Report, Compliment] if user
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
       html=""
       return html if resource.errors.empty?

       errors_number = 0

       html << '<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a><ul class="'+#{resource_name}+'_errors_list">'

       saved_key = ""
       resource.errors.each do |key, value|
         if key != saved_key
           html << "<li class=\"#{key} error\"> This #{key} #{value} </li>"
           errors_number += 1
         end
         saved_key = key
       end

       unsolved_errors = pluralize(errors_number, "unsolved error")
       #html = "<h2 class=\"#{resource_name}_errors_title\"> You have #{unsolved_errors} </h2>" + html
       html << "</ul></div>"

       return html.html_safe
    end
end

app/views/layouts/admin/_alert.html.erb
<div class="alert alert-danger">
	<a href="#" class="close" data-dismiss="alert">&times;</a>
	<h4><%=t(:error_title)%></h4>
	<p id="notice"><%= alert %></p>
</div>

app/views/layouts/admin/_footer.html.erb
<footer>
	<address>&copy; <a href="https://www.sleepinglion.pe.kr" title="<%=t(:sleepinglion) %>" target="_blank"><%=t(:sleepinglion) %></a> 2017</address>
</footer>

app/views/layouts/admin/_header.html.erb
<!-- start: Header -->
<header>
	<h1 class="col-xs-12 col-sm-4 col-md-3 col-lg-2"><%=link_to admin_path,:class=>"brand" do %><span class="hidden-phone"><%=t(:application_name)%></span><% end %></h1>
	<div id="top_menu">
		<ul class="nav">
			<li class="dropdown">
				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
					<% if current_admin.photo?  %>
					<%=image_tag current_admin.photo.small_thumb %>
					<% end %>&nbsp;
					<%=current_admin.name %>
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to edit_admin_registration_path do %><i class="glyphicon glyphicon-user"></i> <%=t(:admin_profile) %><% end %></li>
					<li><%= link_to destroy_admin_session_path do %><i class="glyphicon glyphicon-off"></i> <%=t(:logout) %><% end %></li>
				</ul>
			</li>
			<li class="dropdown">
				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
					<% if I18n.locale.to_s=='ko' %>
					<%=t(:korean) %>
					<% end %>
					<% if I18n.locale.to_s=='zh-CN' %>
					<%=t(:chineses) %>
					<% end %>
					<% if I18n.locale.to_s=='en' %>
					<%=t(:english) %>
					<% end %>
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<% unless I18n.locale=='ko' %>
					<li><%= link_to url_for(:locale=>'ko') do %><%=t(:korean) %><% end %></li>
					<% end %>
					<% unless I18n.locale=='zh-CN' %>
					<li><%= link_to url_for(:locale=>'zh-CN') do %><%=t(:chineses) %><% end %></li>
					<% end %>
					<% unless I18n.locale=='en' %>
					<li><%= link_to url_for(:locale=>'en') do %><%=t(:english) %><% end %></li>
					<% end %>
				</ul>
			</li>
		</ul>
	</div>
		<nav class="col-xs-12 col-md-8 col-lg-7">
			<%= render :partial => 'layouts/admin/menu' %>
		</nav>
</header>
<!-- start: Header -->

app/views/layouts/admin/_menu.html.erb
<ul class="nav main-menu">
	<% if can? :read, User %>
	<li class="dropdown">
		<a class="dropdown-toggle dropmenu<% if params[:controller]=='admin/users' %> active<% end %>" data-toggle="dropdown" href="#">
			<i class="glyphicon glyphicon-user glyphicon-white"></i>
			<%=t(:menu_user,scope:[:admin_menu]) %>
			<span class="caret"></span>
		</a>
		<ul	class="dropdown-menu<% if params[:controller]=='admin/operators' || params[:controller]=='admin/users' || params[:controller]=='admin/groups' || params[:controller]=='admin/kits' %> current<% end %>">
			<% if can? :read, User %>
			<li<% if params[:controller]=='admin/users' %> class="active"<% end %>><%=link_to admin_users_path do %>
				<i class="glyphicon glyphicon-user glyphicon-white"></i>
				<%=t(:user,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
		</ul>
	</li>
	<% end %>

	<% if can?(:read, ReportCategory) || can?(:read, Report) || can?(:read, ComplimentCategory) || can?(:read, Bank) || can?(:read, Compliment) || can?(:read, FaqCategory) || can?(:read, Faq)%>
	<li class="dropdown">
		<a class="dropdown-toggle dropmenu<% if params[:controller]=='admin/report_categories' || params[:controller]=='admin/reports' || params[:controller]=='admin/compliment_categories'|| params[:controller]=='admin/banks' || params[:controller]=='admin/compliments' || params[:controller]=='admin/faq_categories' || params[:controller]=='admin/faqs'  %> active<% end %>" data-toggle="dropdown" href="#">
			<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
			<%=t(:menu_main_board,scope:[:admin_menu]) %>
			<span class="caret"></span>
		</a>
		<ul	class="dropdown-menu<% if params[:controller]=='admin/report_categories' || params[:controller]=='admin/reports' || params[:controller]=='admin/compliment_categories'|| params[:controller]=='admin/banks' || params[:controller]=='admin/compliments' || params[:controller]=='admin/faq_categories' || params[:controller]=='admin/faqs'  %> current<% end %>">
			<% if can? :read, ReportCategory %>
			<li<% if params[:controller]=='admin/report_categories' %> class="active"<% end %>><%=link_to admin_report_categories_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:report_category,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
			<% if can? :read, Report %>
			<li<% if params[:controller]=='admin/reports' %> class="active"<% end %>><%=link_to admin_reports_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:report,scope:[:activerecord,:models])%><% end %></li>
			<% end %>

			<% if can? :read, ComplimentCategory %>
			<li<% if params[:controller]=='admin/compliment_categories' %> class="active"<% end %>><%=link_to admin_compliment_categories_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:compliment_category,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
			<% if can? :read, Bank %>
			<li<% if params[:controller]=='admin/banks' %> class="active"<% end %>><%=link_to admin_banks_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:bank,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
			<% if can? :read, Compliment %>
			<li<% if params[:controller]=='admin/compliments' %> class="active"<% end %>><%=link_to admin_compliments_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:compliment,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
				<% if can? :read, FaqCategory %>
				<li<% if params[:controller]=='admin/faq_categories' %> class="active"<% end %>><%=link_to admin_faq_categories_path do %>
					<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
					<%=t(:faq_category,scope:[:activerecord,:models])%><% end %></li>
				<% end %>
				<% if can? :read, Faq %>
				<li<% if params[:controller]=='admin/faqs' %> class="active"<% end %>><%=link_to admin_faqs_path do %>
					<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
					<%=t(:faq,scope:[:activerecord,:models])%><% end %></li>
				<% end %>
		</ul>
	</li>
	<% end %>


	<% if can?(:read, Propose) || can?(:read, Model) || can?(:read, Improve) || can?(:read, Article) %>
	<li class="dropdown">
		<a class="dropdown-toggle dropmenu<% if params[:controller]=='admin/proposes' || params[:controller]=='admin/models' || params[:controller]=='admin/improve' || params[:controller]=='admin/articles' %> active<% end %>" data-toggle="dropdown" href="#">
			<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
			<%=t(:menu_etc_board,scope:[:admin_menu]) %>
			<span class="caret"></span>
		</a>
		<ul	class="dropdown-menu<% if params[:controller]=='admin/proposes' || params[:controller]=='admin/models' || params[:controller]=='admin/improve' || params[:controller]=='admin/articles' %> current<% end %>">
			<% if can? :read, Propose %>
			<li<% if params[:controller]=='admin/proposes' %> class="active"<% end %>><%=link_to admin_proposes_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:propose,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
			<% if can? :read, Model %>
			<li<% if params[:controller]=='admin/models' %> class="active"<% end %>><%=link_to admin_models_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:model,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
			<% if can? :read, Improve %>
			<li<% if params[:controller]=='admin/improve' %> class="active"<% end %>><%=link_to admin_improve_index_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:improve,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
			<% if can? :read, Article %>
			<li<% if params[:controller]=='admin/articles' %> class="active"<% end %>><%=link_to admin_articles_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:article,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
			<% if can? :read, Notice %>
			<li<% if params[:controller]=='admin/notices' %> class="active"<% end %>><%=link_to admin_notices_path do %>
				<i class="glyphicon glyphicon-list-alt glyphicon-white"></i>
				<%=t(:notice,scope:[:activerecord,:models])%><% end %></li>
			<% end %>
		</ul>
	</li>
	<% end %>

</ul>

app/views/layouts/admin/_notice.html.erb
<div class="alert alert-success">
	<a href="#" class="close" data-dismiss="alert">&times;</a>
	<!-- <h4><%=t(:success_title)%></h4> -->
	<p id="notice"><%= notice %></p>
</div>

app/views/layouts/admin/_search_form.erb
<div class="input-group">
	<div class="input-group-btn">
		<button aria-expanded="false" data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button"><%=search_type %>
			&nbsp;
			<span class="caret"></span>
		</button>
		<ul role="menu" class="dropdown-menu">
			<li>
				<a href="?search_type=title"><%=title %></a>
			</li>
			<li>
				<a href="?search_type=sub_title"><%=sub_title %></a>
			</li>
		</ul>
	</div>
	<select name="search_type" style="display:none">
		<option value="title" <% if params[:search_type].present? %><% if params[:search_type]=='title' %>selected="selected"<% end %><% else %>selected="selected"<% end %>><%=t(:label_title)%></option>
		<option value="sub_title" <% if params[:search_type].present? %><% if params[:search_type]=='sub_title' %>selected="selected"<% end %><% end %>><%=t(:label_sub_title)%></option>
	</select>
	<input type="search" required="required" maxlength="60" placeholder="<%=t(:insert_search_word) %>" value="<%=params[:search_value] %>" class="form-control" name="search_value"/>
	<span class="input-group-btn">
		<%=button_tag t(:search),:type=>'submit',:class=>"btn btn-default" %>
	</span>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale %>">
<head>
  <meta charset="utf-8" />
  <title><%=t(:application_name)%></title>
  <meta name="description" content="<%=t(:application_name)%> Admin System" />
  <meta name="author" content="Sleeping-Lion" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%= stylesheet_link_tag 'admin/application', :media=>'all', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<![endif]-->
</head>
<body>
	<%= render :partial => 'layouts/admin/header' %>
	<div id="mom" class="container-fluid">
		<div id="main" class="row">
			<div id="content" class="col-12">
				<% unless controller.controller_name=='admin' %>
					<% if(!params[:no_layout] and !current_page?(admin_path)) %>
						<ol class="breadcrumb">
							<li><%= link_to t(:home),root_path %></li>
							<% if(@category.present?) %>
							<li><a href="#"><%= @category %></a><% if(@controller_name) %><% end %></li>
							<% end %>
							<li><a href="#"><%= @controller_name %></a></li>
							<li><a href="#"><%=actionNameChange controller.action_name %></a></li>
						</ol>
						<hr class="hidden-xs" />
					<% end %>
					<% end %>
					<% if notice %>
					<%= render 'layouts/admin/notice',:locals=>{:notice=>notice} %>
					<% end %>
					<% if alert %>
					<%= render 'layouts/admin/alert',:locals=>{:alert=>alert} %>
					<% end %>
						<%= yield %>
					</div>
				</div><!--/#content.span10-->
			</div>
	<%= render 'layouts/admin/footer' %>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog"></div>
	<%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale %>">
<head>
  <meta charset="utf-8">
  <title><%=t(:application_name)%></title>
  <meta name="description" content="<%=t(:application_name)%>">
  <meta name="author" content="Sleeping-Lion">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag "admin/application", :media => "all", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!--[if IE]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <![endif]-->
</head>
<body id="anon_body">
<div id="mom">
  <div id="main">
    <div class="sub_main">
      <%= yield %>
    </div>
  </div>
</div>
<%= render :partial => 'layouts/admin/footer' %>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"></div>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>