config/routes.rb
AntiKb::Application.routes.draw do
  root 'home#index'

  if Rails.env.production?
    mount LetsEncrypt::Engine => '/.well-known'
  end


  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords" }, :path_names => { :sign_up => 'new', :sign_in => 'login', :sign_out => 'logout' }
  as :user do
    get '/users/presign', to: 'users/sessions#presign', as: :user_presign
  end

  resources :users do
    member do
      put 'like', to: 'users#upvote'
      put 'dislike', to: 'users#downvote'
    end
  end

  resources :reports do
    member do
      put 'like', to: 'reports#upvote'
      put 'dislike', to: 'reports#downvote'
    end
  end

  resources :compliments do
    member do
      put 'like', to: 'compliments#upvote'
      put 'dislike', to: 'compliments#downvote'
    end
  end

  resources :models do
    member do
      put 'like', to: 'models#upvote'
      put 'dislike', to: 'models#downvote'
    end
  end

  resources :comments, only: :destroy

  resources :articles, :intro, :improve, :sitemap, :faqs, :faq_categories, :proposes, :notices, :galleries
  get 'kbsmind', to: 'home#kbsmind'
  get 'feed', to: 'home#feed'
  get 'privacy', to: 'home#privacy'
  get 'user-delete-confirm', :to=>'users#delete_confirm', as: 'delete_confirm_user'
  get 'users/add_new_comment/:id', to: 'users#new_comment', as: 'new_comment_to_users'
  post 'users/add_new_comment', to: 'users#create_comment', as: 'create_comment_to_users'

  get 'home', to: 'home#index'
  scope 'admin', module: 'admin', as: 'admin' do
    get '/' => 'admin_home#index'
    resources :users, :articles, :improve, :faq_categories, :faqs, :proposes, :compliment_categories, :compliments, :report_categories, :reports, :notices, :models, :banks
  end
end

app/models/report.rb
class Report < ApplicationRecord
  acts_as_votable
  acts_as_commentable
  is_impressionable
  validates_presence_of :title
  belongs_to :user, counter_cache: true
  belongs_to :report_category, counter_cache: true
  has_one :report_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :report
  accepts_nested_attributes_for :report_content, :allow_destroy => true, :update_only => true

  def report_content
    super || build_report_content
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController
  before_action :set_admin_report, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)

    @category = t(:menu_main_board,scope:[:admin_menu])
    @controller_name = t('activerecord.models.report')
  end

  # GET /admin/reports
  # GET /admin/reports.json
  def index
    @admin_reports = Report.order('id desc').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_reports }
    end
  end

  # GET /admin/reports/1
  # GET /admin/reports/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_report }
    end
  end

  # GET /admin/reports/new
  # GET /admin/reports/new.json
  def new
    @admin_report = Report.new
    @admin_report.build_report_content

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_report }
    end
  end

  # GET /admin/reports/1/edit
  def edit
  end

  # POST /admin/reports
  # POST /admin/reports.json
  def create
    @admin_report = Report.new(admin_report_params)

    respond_to do |format|
      if @admin_report.save
        format.html { redirect_to admin_reports_url, notice: @controller_name + t(:message_success_create) }
        format.json { render json: @admin_report, status: :created, location: @admin_report }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/reports/1
  # PUT /admin/reports/1.json
  def update
    respond_to do |format|
      if @admin_report.update_attributes(admin_report_params)
        format.html { redirect_to admin_reports_url, notice: @controller_name + t(:message_success_update) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/reports/1
  # DELETE /admin/reports/1.json
  def destroy
    @admin_report.destroy

    respond_to do |format|
      format.html { redirect_to admin_reports_path}
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_admin_report
    @admin_report = Report.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_report_params
    params.require(:report).permit(:report_category_id, :title, :enable, report_content_attributes: [:id, :content]).merge(user_id: current_admin.id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < BoardController
  load_and_authorize_resource  except: [:index, :show, :create]
  impressionist :actions=>[:show]
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)
    @controller_name=t('activerecord.models.report')
    @title=@controller_name
  end

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.order('id desc').page(params[:page]).per(10)

    respond_to do |format|
      format.html { render layout: layout } # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @title=@report.title
    @meta_description=@report.report_content.content
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @report.build_report_content

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
      if @report.user_id!=current_user.id
        redirect_to @report, :alert=> "권한이 없습니다."
      end
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, :notice=> @controller_name +t(:message_success_create)}
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update_attributes(report_params)
        format.html { redirect_to @report, :notice=> @controller_name +t(:message_success_update)}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  def upvote
    respond_to do |format|
      if @report.liked_by current_user
        format.html { redirect_to report_path(@report), :notice => t(:message_success_recommend)}
        format.json { render :json => {vote_up: @report.cached_votes_up}}
      else
        format.html { render :action => "index" }
        format.json { render :json => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  def downvote
    respond_to do |format|
      if @report.downvote_from current_user
        format.html { redirect_to report_path(@report), :notice => t(:message_success_recommend)}
        format.json { render :json => {vote_up: @report.cached_votes_down}}
      else
        format.html { render :action => "index" }
        format.json { render :json => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:report_category_id, :title, report_content_attributes: [:content]).merge(user_id: current_user.id)
    end
end

app/views/reports/_form.html.erb
<%= form_for @report, :html => { :class => 'col-12' } do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>
      <ul>
        <% @report.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :report_category_id, :class => 'control-label' %>
    <%= f.select :report_category_id, options_from_collection_for_select(ReportCategory.where(:enable => true).all, 'id', 'title', @report.report_category_id), {}, { :class => "form-control input-lg" } %>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label' %>
    <%= f.text_field :title, :class => 'form-control input-lg', :required => 'required' %>
  </div>
  <%= f.fields_for :report_content do |c| %>
    <div class="form-group">
      <%= c.label :content, :class => 'control-label' %>
      <%= c.text_area :content, :class => 'form-control input-lg', :rows => 7, :required => 'required' %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit :class => 'btn btn-lg btn-block btn-primary' %>
  </div>
<% end %>

app/views/reports/_index.html.erb
<article class="col-12 col-md-6">
	<h3><%=t(:report,scope:[:activerecord,:models]) %></h3>
	<%=link_to t(:link_more),reports_path,:class=>'more' %>
	<% unless @reports.empty? %>
	<ul>
		<% @reports.each do |report| %>
		<li><%=report.user.name %> : <%=link_to report.title.truncate(17),report %> <span class="date d-md-none d-lg-block"><%=get_dt_format report.created_at.to_date %></span></li>
		<% end %>
	</ul>
	<% else %>
	<p><%=t(:no_data) %></p>
	<% end %>
</article>

app/views/reports/edit.html.erb
<div id="report_edit" class="sub_main row">
  <%= render 'form' %>
  <div class="col-12">
    <%= link_to t(:link_show), @report %> |
    <%= link_to t(:link_list), reports_path %>
  </div>
</div>

app/views/reports/index.html.erb
<% breadcrumb :reports %>
<div class="sub_main row">
  <article id="report_main" class="col-12">
    <div class="table-responsive">
      <table class="table">
        <colgroup>
          <col style="width:10%">
          <col style="wdith:20%">
          <col>
          <col style="wdith:10%">
          <col style="wdith:10%">
          <col style="wdith:10%">
        </colgroup>
        <thead class="thead-default">
        <tr>
          <th class="text-center"><%= t(:user_id, scope: [:activerecord, :attributes, :report]) %></th>
          <th><%= t(:report_category_id, scope: [:activerecord, :attributes, :report]) %></th>
          <th><%= t(:title, scope: [:activerecord, :attributes, :report]) %></th>
          <th class="text-right sl_count"><%= t(:label_count) %></th>
          <th class="text-right sl_recommend"><%= t(:label_recommend_count) %></th>
          <th class="text-right sl_registered_date"><%= t(:label_created_at) %></th>
        </tr>
        </thead>
        <tbody>
        <% unless @reports.empty? %>
          <% @reports.each do |report| %>
            <tr>
              <td><%= report.user.name %></td>
              <td><%= report.report_category.title %></td>
              <td><%= link_to report.title.truncate(25), report %></td>
              <td class="text-right sl_count"><%= report.default_view_count + report.impressionist_count(:filter => :ip_address) %></td>
              <td class="text-right sl_count"><%= report.cached_votes_up %></td>
              <td class="text-right sl_registered_date"><%= get_dt_format(report.created_at.to_date) %></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="6"><%= t(:no_data) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @reports %>
  </article>
  <div class="col-12">
    <%= link_to t(:link_new), new_report_path %>
  </div>
</div>

app/views/reports/new.html.erb
<div id="report_new" class="sub_main row">
  <%= render 'form' %>
  <div class="col-12">
    <%= link_to t(:link_list), reports_path %>
  </div>
</div>

app/views/reports/show.html.erb
<% breadcrumb :report, @report %>
<div id="report_show" class="sub_main row">
  <div class="slboard_content col-12" itemscope itemprop="article" itemtype="http://schema.org/Article">
    <div class="sl_content_header">
      <h3 itemprop="name"><%= @report.title %></h3>
      <p>
        <%= t(:user_id, scope: [:activerecord, :attributes, :report]) %> :
        <span itemprop="author"><%= link_to @report.user.name, user_path(@report.user) %></span>&nbsp;
        <%= t(:label_created_at) %> : <span><%= get_dt_format(@report.created_at.to_date) %></span>
        <span class="none" itemprop="dateCreated"><%= @report.created_at %></span>
        <span class="none" itemprop="dateModified"><%= @report.updated_at %></span>
      </p>
    </div>
    <div class="sl_content_main">
      <div class="sl_content_text" itemprop="text"><%= simple_format(@report.report_content.content) %></div>
      <div class="vote">
        <% if user_signed_in? %>
          <%= link_to like_report_path(@report), method: :put do %>
            <span class="material-icons
              <% if current_user.voted_for? @report %> already-vote
              <% end %>">thumb_up</span> <span class="text"><%= @report.cached_votes_up %></span>
          <% end %>
        <% else %>
          <%= link_to like_report_path(@report), { method: :put, :class => "confirm_login" } do %>
            <span class="material-icons">thumb_up</span> <span class="text"><%= @report.cached_votes_up %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div id="sl_content_bottom_menu">
    <%= link_to t(:link_new), new_report_path %> &nbsp; | &nbsp;
    <%= link_to t(:link_list), reports_path %>
    <% if can? :update, @report and @report.user_id == current_user.id %>
      &nbsp; | &nbsp;
      <%= link_to t(:link_edit), edit_report_path(@report) %>
    <% end %>
  </div>
</div>